media:
  input: static/images
  output: /images

content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    fields:
      - name: title
        type: string
      - name: category
        type: select
        options:
          values:
            - Spiritual
            - Technical
            - Design
            - Personal Development
      - name: body
        type: rich-text
      - name: date
        type: date
      - name: tags
        type: string
        list: true

  - name: portfolio
    label: Portfolio
    type: collection
    path: content/portfolio
    fields:
      - name: title
        type: string
      - name: thumbnail
        label: Project Thumbnail
        type: image
      - name: body
        type: rich-text
      - name: order-number 
        type: number 
      - name: tags
        type: string
        list: true

  - name: resources
    label: Resources
    type: collection
    path: content/resources
    fields:
      - name: title
        type: string
      - name: thumbnail
        label: Resource Thumbnail
        type: image
      - name: body
        type: rich-text
      - name: tags
        type: string
        list: true
      - name: slider_images
        label: Wallpaper Gallery
        type: object
        list: true
        fields:
          - name: image
            label: Wallpaper Image
            type: image
          - name: description
            label: Description / Caption
            type: string