media:
  input: static/images
  output: /images
content:
  - name: articles
    label: Articles
    type: collection
    path: content/articles
    fields:
      - name: title
        type: string
      - name: body
        type: rich-text