backend:
  name: github
  repo: samathaom/SamathaOm  # Verified from your logs
  branch: main
  base_url: https://samathaom.vercel.app # Add this!
  auth_endpoint: api/index # This points to /api/index.js

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}